#!/bin/bash

# Delete the link to the binary
if type update-alternatives >/dev/null 2>&1; then
    update-alternatives --remove 'cdapuestas-webview' '/usr/bin/cdapuestas-webview'
else
    rm -f '/usr/bin/cdapuestas-webview'
fi
