#!/bin/bash

if type update-alternatives 2>/dev/null >&1; then
    # Remove previous link if it doesn't use update-alternatives
    if [ -L '/usr/bin/cdapuestas-webview' -a -e '/usr/bin/cdapuestas-webview' -a "`readlink '/usr/bin/cdapuestas-webview'`" != '/etc/alternatives/cdapuestas-webview' ]; then
        rm -f '/usr/bin/cdapuestas-webview'
    fi
    update-alternatives --install '/usr/bin/cdapuestas-webview' 'cdapuestas-webview' '/opt/cdapuestas_webview/cdapuestas-webview' 100 || ln -sf '/opt/cdapuestas_webview/cdapuestas-webview' '/usr/bin/cdapuestas-webview'
else
    ln -sf '/opt/cdapuestas_webview/cdapuestas-webview' '/usr/bin/cdapuestas-webview'
fi

# Check if user namespaces are supported by the kernel and working with a quick test:
if ! { [[ -L /proc/self/ns/user ]] && unshare --user true; }; then
    # Use SUID chrome-sandbox only on systems without user namespaces:
    chmod 4755 '/opt/cdapuestas_webview/chrome-sandbox' || true
else
    chmod 0755 '/opt/cdapuestas_webview/chrome-sandbox' || true
fi

if hash update-mime-database 2>/dev/null; then
    update-mime-database /usr/share/mime || true
fi

if hash update-desktop-database 2>/dev/null; then
    update-desktop-database /usr/share/applications || true
fi
